name: Deploy React App to GitHub Pages (Debuggable)

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Show build files (debug)
        run: |
          echo "ROOT of build:"
          ls -la build || true
          echo ""
          echo "CSS files:"
          ls -la build/static/css || true
          echo ""
          echo "JS files:"
          ls -la build/static/js || true
          echo ""
          echo "index.html head:"
          head -n 40 build/index.html || true

      - name: Upload build artifact (for manual inspection)
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: build

      - name: Copy index.html to 404.html
        run: cp build/index.html build/404.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
