name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main   # Deploy on every push to main

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3️⃣ Setup Yarn
      - name: Setup Yarn
        uses: borales/actions-yarn@v4
        with:
          version: 3.5.1  # Stable Yarn version

      # 4️⃣ Cache Yarn dependencies
      - name: Cache Yarn
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
            ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      # 5️⃣ Install dependencies with frozen lockfile
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # 6️⃣ Build project
      - name: Build project
        run: yarn build

      # 7️⃣ Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
