name: Deploy React App to GitHub Pages

# Trigger on pushes to main
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1) Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2) Setup Node.js and enable caching for Yarn
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'yarn'

      # 3) Enable Corepack and prepare Yarn
      - name: Enable Corepack and prepare Yarn
        run: |
          corepack enable
          corepack prepare yarn@stable --activate

      # 4) Cache Yarn/Berry to speed up builds
      - name: Cache Yarn (Berry)
        uses: actions/cache@v4
        with:
          path: |
            .yarn/cache
            .yarn/unplugged
            .yarn/build-state.yml
            node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      # 5) Install dependencies
      - name: Install dependencies
        run: yarn install --immutable

      # 6) Build the React app
      - name: Build
        run: yarn build

      # 7) Deploy to GitHub Pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v7
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
